### ISSUE TITLE
Ninject 3.3.4 compatibility

### ISSUE THREAD

**Issue by DzonnyDZ** [ninject/Ninject.Web#16]
I was trying to update all nInject packages in my solution and I realized I cannot update to latest nInject 3.3.4 because nInject.Web has dependency Ninject (>= 3.2.0 && < 3.3.0).

Can this package be updated for compatibility with nInject 3.3.4.

I would do the change even myself and issues a pull request but I don't know how this package has been built so how would I test it.

**Comment by DzonnyDZ** [comment]
I managed to make working version by disassembly of original Ninject.Web. I'm attaching here the source code and binaries for reference...

[Ninject.Web.3.3.4.NuGet.zip](https://github.com/ninject/Ninject.Web/files/2221474/Ninject.Web.3.3.4.NuGet.zip)
[Ninject.Web.src.zip](https://github.com/ninject/Ninject.Web/files/2221475/Ninject.Web.src.zip)

**Comment by eric-git** [comment]
Hope we can fix this issue ASAP. I am unable to upgrade my packages.

**Comment by BloodBaz** [comment]
This problem has been plaguing me for nearly a year now.  Looking at the 3 modules: `Ninject.Web`,  `Ninject.Web.Common`,  `Ninject.Web.Common.WebHost` , it looks like that the last two module's version upgrade from v3.2.3 to v3.3.1 has included migrating some code from one module to the other?   According to the semantic versioning, these changes shouldn't be breaking but I think they are.  And should `Ninject.Web` not be updated to include v3.3.1 of `Ninject.Web.Common`,  `Ninject.Web.Common.WebHost` modules?  What doesn't help is that all documentation online is pre -v3.3.1 so is out of date.

**Comment by BloodBaz** [comment]
I've written instructions on how to upgrade here: https://stackoverflow.com/questions/52272485/cannot-upgrade-ninject-to-latest-version-in-nuget/52278129

**Comment by xhafan** [comment]
I was playing with ASP.NET WebForms app, and wanted to add 3.3.x Ninject packages, but discovered that Ninject.Web does not exist in 3.3.x version. Without this package, "in request scope" resolution does not work. I tried to add Ninject.MVC5 package even though it's a web forms app and not MVC app, and "in request scope" resolution started working. Not really happy about it, but as a workaround it's working.

**Comment by scott-xu** [comment]
Fixed in Release 3.3.0
