### ISSUE TITLE
NinjectWebCommon bootstrapping appears broken.

### ISSUE THREAD

**Issue by Boggin** [ninject/Ninject.Web#7]
I've tested the bootstrapping in NinjectWebCommon by creating a new ASP.NET Web Forms Site using VS2012 and adding a Services project with a DummyService. I can get my example to work with an override of CreateKernel in Global.asax but not if I use the Bootstrapper. Also, my WebForm pages must inherit from Ninject.Web.PageBase to work.

I've pushed my DemoNinject web site up to github to illustrate what works and what doesn't: https://github.com/Boggin/DemoNinject

**Comment by scott-xu** [comment]
Fixed in Release 3.3.0
